name: 'Debug Tests'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'

jobs:
  complex:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run performance tests
      uses: ./
      with:
        urls: |
          /
          /wp-admin/
        plugins: |
          ./tests/dummy-plugin
        blueprint: './tests/performance-blueprint.json'
        iterations: 5
        repetitions: 1
