name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

# Here's where the plugin/theme would run their custom build process
# and then provide their slug to the action for installing it.

    - name: Run performance tests
      uses: ./
      with:
        urls: |
          /
          /sample/page/
