name: 'Test with PR comment'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'

jobs:
  basic:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run performance tests
      uses: ./
      with:
        urls: |
          /
          /sample-page/
        create-comment: true
        github-token: ${{ secrets.PR_COMMENT_TOKEN }}
