name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'

jobs:
  complex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run performance tests
      uses: ./
      with:
        urls: |
          /
          /sample/page/
        plugins: |
          ./dummy-plugin
          https://downloads.wordpress.org/plugin/performant-translations.zip
          https://downloads.wordpress.org/plugin/wordpress-seo.zip
        iterations: 5
        repetitions: 1
